// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv4crOrf4KacTiArfBlEyYD7j9YbIN-ss',
    appId: '1:363143764724:web:8f17efa045cbd8c4655ca1',
    messagingSenderId: '363143764724',
    projectId: 'insta-clone-fafa7',
    authDomain: 'insta-clone-fafa7.firebaseapp.com',
    storageBucket: 'insta-clone-fafa7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5fyWleMz8t3vb9ppJbOW1BdAzcwEYtFo',
    appId: '1:363143764724:android:9314f8f6d05dadf5655ca1',
    messagingSenderId: '363143764724',
    projectId: 'insta-clone-fafa7',
    storageBucket: 'insta-clone-fafa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDkyVf4BeZDvbh2lAI5FBfDpNzMHMzqQ',
    appId: '1:363143764724:ios:b296d6024a97156f655ca1',
    messagingSenderId: '363143764724',
    projectId: 'insta-clone-fafa7',
    storageBucket: 'insta-clone-fafa7.firebasestorage.app',
    iosBundleId: 'com.example.socialBloc',
  );
}
